language: c
sudo: false
dist: trusty
compiler:
    #- clang
    - gcc
os:
- linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov
  
branches:
  - master
  - develop

before_script:
  - mkdir build
  - cd build
  #- cmake -DCMAKE_C_FLAGS="-Wall -fprofile-arcs -ftest-coverage -fprofile-generate -lgcov --coverage" ../RTG-scheduler
  - cmake -DCMAKE_C_FLAGS="-Wall -fprofile-arcs -ftest-coverage -std=c99" ../RTG-scheduler

script: 
  - make 

after_success:
  #- cd ${TRAVIS_BUILD_DIR}
  - ./../RTG-scheduler/testScripts/runCodeCoverage.sh
  - ./bin/RTG-scheduler --j testData/set1-jobs.txt --rt testData/set1-jobReleaseTimes.txt
  - ./bin/RTG-scheduler --j testData/set1-jobs.txt --rt testData/set1-jobReleaseTimes.txt --m 1
  - ./bin/RTG-scheduler --j testData/set1-jobs.txt --rt testData/set1-jobReleaseTimes.txt --m 2
  - ./bin/RTG-scheduler --j testData/set1-jobs.txt --rt testData/set1-jobReleaseTimes.txt --m 3
  - ./bin/RTG-scheduler --j testData/set1-jobs.txt --rt testData/set1-jobReleaseTimes.txt --m 4
  - ./bin/RTG-scheduler --j testData/set1-jobs.txt --rt testData/set1-jobReleaseTimes.txt --m 5
  - ./bin/RTG-scheduler --j testData/set1-jobs.txt --rt testData/set1-jobReleaseTimes.txt --m 99 
  - ./bin/RTG-scheduler --h
  - ./bin/RTG-scheduler --j
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  # Uploading report to CodeCov
  #- bash <(curl -s https://codecov.io/bash)
  - bash <(curl -s https://codecov.io/bash) || echo "codecov did not collect coverage reports"

notifications:
  email:
    - kiritigowda@gmail.com
